apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-shop-backend-uploads
  namespace: online-shop
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi