apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-shop-backend-uploads
  namespace: online-shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi