apiVersion: apps/v1
kind: Deployment

metadata:
  name: online-shop-backend
  namespace: online-shop
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  replicas: 1

  selector:
    matchLabels:
      app: online-shop-backend

  template:
    metadata:
      labels:
        app: online-shop-backend

    spec:
      containers:
        - name: backend
          image: yazeeth/onlineshop-backend:v1.0.4
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: online-shop-backend-config
            - secretRef:
                name: online-shop-backend-secret