apiVersion: v1
kind: Service

metadata:
  name: online-shop-backend
  namespace: online-shop

spec:
  selector:
    app: online-shop-backend

  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050