apiVersion: apps/v1
kind: Deployment

metadata:
  name: online-shop-backend
  namespace: online-shop
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  replicas: 1

  selector:
    matchLabels:
      app: online-shop-backend

  template:
    metadata:
      labels:
        app: online-shop-backend

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "online-shop"
        vault.hashicorp.com/agent-inject-secret-database-url: "secret/data/online-shop"
        vault.hashicorp.com/agent-inject-template-database-url: |
          {{- with secret "secret/data/online-shop" -}}
          {{ .Data.data.DATABASE_URL }}
          {{- end }}

    spec:
      serviceAccountName: online-shop-backend

      containers:
        - name: backend
          image: yazeeth/onlineshop-backend:v1.0.5
          ports:
            - containerPort: 5050
          command: ["/bin/sh", "-c"]
          args:
            - |
              export DATABASE_URL="$(cat /vault/secrets/database-url)"
              exec npm start

          envFrom:
            - configMapRef:
                name: online-shop-backend-config