apiVersion: v1
kind: Service

metadata:
  name: online-shop-frontend
  namespace: online-shop

spec:
  type: NodePort

  selector:
    app: online-shop-frontend

  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30173
