# SAMPLE ONLY — DO NOT USE REAL CREDENTIALS

apiVersion: v1
kind: Secret

metadata:
  name: online-shop-postgres-secret
  namespace: online-shop

type: Opaque

stringData:
  POSTGRES_DB: "onlineshop"
  POSTGRES_USER: "shopuser"
  POSTGRES_PASSWORD: "CHANGE_ME"