apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# images:
#   - name: yazeeth/onlineshop-backend
#     newTag: v1.0.3
#   - name: yazeeth/onlineshop-frontend
#     newTag: v1.0.3
