apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yazeeth/online-shop-gitops.git
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true