apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-local
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/yazeeth/online-shop-gitops.git
    targetRevision: main
    path: apps/online-shop/overlays/local

  destination:
    server: https://kubernetes.default.svc
    namespace: online-shop

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
